mongo.host=localhost
mongo.port=27017
mongo.database=appdb
mongo.username=admin
mongo.password=appdb

mp.jwt.verify.issuer=LakerTracks
mp.jwt.verify.publickey.algorithm=RS256
mp.jwt.verify.audiences=worklog
mp.jwt.verify.publickey=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk0IopSGDrrgPc8OGyBa6\nNZNaRnzjJOKvdr5egw00F+ZnEGQYFD1B4vG3B+fqowjvXjiuhvX7ivdmVKA0paHz\nV8lwkp3yoAHRJdCdUbunx/yGAl4NDQvJSAJVYlC75GFDylqALd1eP2AuBHqCYuml\nlTZsJrvzXwk3OaxUrE8ciGixlemE9v24G8+61kFR5tnFp7kvtnxckNshthQ9zhth\nWpdPI75Rp5bZ6Bjroe/HFFraouNtPOr/GnzOfEBVHS1c57KsDCsSupefKt3RzgOz\n9vJooXmbgqN9hY5tT16uR8VoCJWXZHVwuQzSyhhXtznkvN3YcidQ0H56j/zfg5lF\n1wIDAQAB\n-----END PUBLIC KEY-----