# NOTE: mongo.hostname=mongodb in docker
mongo.hostname=localhost
mongo.port=27017
mongo.dbname=appdb
mongo.username=appuser
mongo.password=secret123

mp.jwt.verify.issuer=LakerTracks
mp.jwt.verify.publickey.algorithm=RS256
mp.jwt.verify.audiences=worklog                                                                                                                                                    
mp.jwt.verify.publickey.location=publickey.pem
                                                 

