name: Pull Request Main
on:
    pull_request:
        branches: [main]
jobs:
    build_frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Build Frontend Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./frontend
                  push: false

    build_backend_worklog:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Build Backend Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./backend/worklog
                  push: false

    build_backend_notification:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Build Backend Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./backend/notification
                  push: false

    build_backend_task:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Build Backend Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./backend/task
                  push: false